# GET all cars request
GET http://localhost:8080/cars HTTP/1.1

###

# GET car by id request
GET http://localhost:8080/cars/1 HTTP/1.1

###

# GET all bookings request
GET http://localhost:8080/bookings HTTP/1.1

###

# GET booking by id request
GET http://localhost:8080/bookings/1 HTTP/1.1

###

# POST request to add new car
POST http://localhost:8080/cars HTTP/1.1
Content-Type: application/json

{
    "brand": "TEST",
    "model": "TEST",
    "year": 2023,
    "price": 14.99,
    "bookings": []
}

###

# POST request to add new booking
POST http://localhost:8080/bookings HTTP/1.1
Content-Type: application/json

{
    "startDate": "2023-04-10",
    "endDate": "2023-04-14",
    "bookingPrice": null,
    "car": {
        "carId": 1
    }
}

###

# PUT request to edit car
PUT http://localhost:8080/cars/1 HTTP/1.1
Content-Type: application/json

 {
    "brand": "Toyota Edited",
    "model": "Camry Edited"
  }

###

# PUT request to edit booking
PUT http://localhost:8080/bookings/1 HTTP/1.1
Content-Type: application/json

{
    "startDate": "2023-06-10",
    "endDate": "2023-06-14",
    "bookingPrice": null,
    "car": {
        "carId": 1
    }
}

###

# DELETE request for car
DELETE http://localhost:8080/cars/5 HTTP/1.1

###

# DELETE request for booking
DELETE http://localhost:8080/bookings/1 HTTP/1.1
